version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - net_zero_db:/var/lib/postgresql/data

volumes:
  net_zero_db:
