"""Setup Organization Model

Revision ID: f36ab0aa0551
Revises: 
Create Date: 2024-02-14 14:58:52.554884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36ab0aa0551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    op.execute("CREATE SEQUENCE global_id_seq"),
    sa.Column('global_id', sa.Integer(), server_default=sa.text("nextval('global_id_seq')"), nullable=True),
    sa.Column('org_id', sa.String(length=7), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uprn', sa.BigInteger(), nullable=True),
    sa.Column('org_class', sa.Enum('O', 'S', name='organizationclass'), nullable=False),
    sa.Column('application_status', sa.Enum('CREATED', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_uprn'), 'organizations', ['uprn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_uprn'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.execute("DROP SEQUENCE global_id_seq"),
    # ### end Alembic commands ###
